/**
 * continuum/agents/crucible/crucible-memory-loader.ts
 *
 * Phase A — Manual pre-session loader.
 *
 * Reads cross-session-memory.jsonl, selects approved records,
 * sorts by commit_timestamp ascending, and renders a clean
 * markdown memory file to ~/.openclaw/agents/crucible/MEMORY.md.
 *
 * Run before each Crucible session:
 *   bun continuum/agents/crucible/crucible-memory-loader.ts
 *
 * Phase B (future): integrate this logic into automatic session-start
 * path after Phase A is verified end-to-end.
 *
 * Governed by: PACS-MEM-001 / ADR-037
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const STORE_PATH = join(
  homedir(),
  ".openclaw",
  "agents",
  "crucible",
  "memory",
  "cross-session-memory.jsonl",
);

const OUTPUT_PATH = join(homedir(), ".openclaw", "agents", "crucible", "MEMORY.md");

// ---------------------------------------------------------------------------
// Types (mirrors cross-session-memory-store.ts)
// ---------------------------------------------------------------------------

type LearnerEvidenceReference = {
  source: string;
  anchor: string;
  excerpt: string;
};

type CrossSessionMemoryRecord = {
  memory_commit_id: string;
  reflection_candidate_id: string;
  session_id: string;
  commit_timestamp: string;
  adjudication_outcome: "approved";
  adjudication_rationale: string;
  key_insight: string;
  learner_evidence_references: LearnerEvidenceReference[];
  source_agent: string;
  commit_status: "approved_written";
};

// ---------------------------------------------------------------------------
// Load
// ---------------------------------------------------------------------------

function loadApprovedRecords(): CrossSessionMemoryRecord[] {
  if (!existsSync(STORE_PATH)) {
    console.error(`[crucible-memory-loader] Store not found at: ${STORE_PATH}`);
    process.exit(1);
  }

  const raw = readFileSync(STORE_PATH, "utf8");
  const records: CrossSessionMemoryRecord[] = [];

  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }

    try {
      const record = JSON.parse(trimmed) as CrossSessionMemoryRecord;
      if (record.adjudication_outcome === "approved") {
        records.push(record);
      }
    } catch {
      console.warn(`[crucible-memory-loader] Skipping malformed line: ${trimmed.slice(0, 80)}...`);
    }
  }

  // Sort ascending by commit_timestamp so oldest insight appears first.
  records.sort(
    (a, b) => new Date(a.commit_timestamp).getTime() - new Date(b.commit_timestamp).getTime(),
  );

  return records;
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const min = String(d.getUTCMinutes()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd} ${hh}:${min} UTC`;
}

function renderMemoryFile(records: CrossSessionMemoryRecord[]): string {
  const generated = formatTimestamp(new Date().toISOString());

  const header = `# MEMORY.md — Crucible
## Approved Cross-Session Memory
**Agent:** Crucible — AI Learning Architect
**System:** Continuum — Faheem's PAC System
**Generated:** ${generated}
**Source:** ~/.openclaw/agents/crucible/memory/cross-session-memory.jsonl
**Governance:** PACS-MEM-001 / ADR-037

> This file contains only memory commits that have passed MEMORY_COMMIT_AUTH
> and received MEC adjudication_outcome: "approved". Rejected and quarantined
> candidates are not present. Do not modify this file manually — it is
> regenerated by crucible-memory-loader.ts before each session.

**Total approved commits:** ${records.length}

---

`;

  if (records.length === 0) {
    return header + "_No approved memory commits found._\n";
  }

  const entries = records
    .map((r, i) => {
      const evidenceBlock = r.learner_evidence_references
        .map((e) => `  - **Source:** ${e.source} | **Anchor:** ${e.anchor}\n    > ${e.excerpt}`)
        .join("\n");

      return `## Memory Commit ${i + 1} of ${records.length}

**Commit ID:** \`${r.memory_commit_id}\`
**Candidate ID:** \`${r.reflection_candidate_id}\`
**Session:** ${r.session_id}
**Committed:** ${formatTimestamp(r.commit_timestamp)}

### Key Insight

${r.key_insight}

### Adjudication Rationale

${r.adjudication_rationale}

### Learner Evidence References

${evidenceBlock}

---
`;
    })
    .join("\n");

  return header + entries;
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

function writeOutput(content: string): void {
  const dir = dirname(OUTPUT_PATH);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(OUTPUT_PATH, content, "utf8");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log("[crucible-memory-loader] Loading approved records...");
  const records = loadApprovedRecords();
  console.log(`[crucible-memory-loader] Found ${records.length} approved commit(s).`);

  const content = renderMemoryFile(records);

  writeOutput(content);
  console.log(`[crucible-memory-loader] MEMORY.md written to: ${OUTPUT_PATH}`);

  // Summary to stdout so the operator can confirm without opening the file.
  console.log("\n--- Loaded commits ---");
  for (const r of records) {
    console.log(`  [${formatTimestamp(r.commit_timestamp)}] ${r.memory_commit_id}`);
    console.log(`    Insight: ${r.key_insight.slice(0, 100)}...`);
  }
  console.log("--- End of summary ---\n");
  console.log(
    "[crucible-memory-loader] Phase A complete. Inspect MEMORY.md, then start Crucible Session 2.",
  );
}

main();
